######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 25 01:44:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Color.h Manipulator.h Reader.h Renderer.h Sequence.h
SOURCES += Color.cpp \
           ErroringFacility.cpp \
           genome_skittle.cpp \
           Manipulator.cpp \
           Reader.cpp \
           Renderer.cpp \
           Sequence.cpp
