######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 9 19:53:39 2011
######################################################################

QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Color.h \
           Interpreter.h \
           Manipulator.h \
           Reader.h \
           Renderer.h \
           Sequence.h \
           TextureRenderer.h
SOURCES += Color.cpp \
           ErroringFacility.cpp \
           genome_skittle.cpp \
           Interpreter.cpp \
           Manipulator.cpp \
           PointRenderer.cpp \
           Reader.cpp \
           Renderer.cpp \
           Sequence.cpp \
           TextureRenderer.cpp
