######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 26 19:47:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Color.h Interpreter.h Manipulator.h Reader.h Renderer.h Sequence.h
SOURCES += Color.cpp \
           ErroringFacility.cpp \
           genome_skittle.cpp \
           Interpreter.cpp \
           Manipulator.cpp \
           Reader.cpp \
           Renderer.cpp \
           Sequence.cpp
